//
//  MockingBirdSample-MockingBirdSampleMocks.generated.swift
//  MockingBirdSample
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import MockingBirdSample
@testable import Mockingbird
import Foundation
import Swift
import UIKit

// No mocks used in 'MockingBirdSampleTests'. Mockingbird is configured to only generate mocks for
// types that are explicitly initialized in your tests with `mock(SomeType.self)`. For more
// information, see 'Thunk Pruning' in the README.
