# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MinimizePanTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MinimizePanTest
  pod 'SnapKit', '~> 5.0.0'
  pod 'Movin'
  pod 'ARNTransitionAnimator'
  pod 'Hero'

end
