# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftLintSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftLint'
pod 'Alamofire', '~> 5.2'

  # Pods for SwiftLintSample

end
