# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTableViewTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTableViewTest
  pod "SkeletonView"
  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  
end
