# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'FlexibleModelProtocol'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 6.0'
  
  # Pods for MoyaSample

end
