# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
def common_pods
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'FlexibleModelProtocol'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 6.0'
end

target 'MoyaSample' do
  common_pods
end

target 'MoyaSampleTests' do
  common_pods
end
