# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'FlexibleModelProtocol', '~> 1.1'  

  # Pods for MyWidgetExtension

end

target 'WidgetTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WidgetTest

end
