# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NimbleSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NimbleSample

  target 'NimbleSampleTests' do
    inherit! :search_paths
pod 'Quick'
pod 'Nimble'
    # Pods for testing
  end

  target 'NimbleSampleUITests' do
    # Pods for testing
  end

end


