# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactorKitRestfulExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactorKitRestfulExample
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'ReactorKit'

end
