# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseCrashlyticsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Crashlytics'

# Recommended: Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
  # Pods for FirebaseCrashlyticsTest

end
